version: '3.8'

services:
  
  app_api:
    image: dummyicecreamfactoryapi
    container_name: api
    environment:
      - ConnectionStrings__IceCreamDb=Host=app_db;Database=icecreamfactory;Username=postgres;Password=postgres
    depends_on: 
      - "app_db"
    ports: 
      - "8080:8080"
    build:
      context: .
      dockerfile: DummyIceCreamFactoryApi/Dockerfile
    networks:
      - network-bridge
      
  app_db:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=icecreamfactory
    ports:
      - "5432:5432"
    restart: always
    networks:
      - network-bridge

#cache
#blob

networks:
  network-bridge: